server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://dpg-cq5v2u5ds78s73d9cr80-a:5432/meze_db_o5ye
    username: meze
    password: mJhVIy0wm5MQT7YxBgNv1YXXuYtOPFHs
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: mezedukkan915@gmail.com
    password: odvfwnkqolmznhpi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true
  #image
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  profiles:
    active: dev

logging:
  file:
    name: log/meze.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]' : WARN
    '[org.hibernate]' : INFO
    '[org.mezes]' : DEBUG

management: #actuator
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

meze:
  app:
    jwtSecret: MezeDukkaniAppBurayaEklendiBaskaBirIsteginizVarsaSoyleyin+/=123
    jwtExpirationMs: 86400000
    mailAddress: mezedukkan915@gmail.com
    backendLink: https://ecommerce-backend-v2.herokuapp.com/
    resetPasswordLink: https://meze-dukkani.onrender.com/

info:
  application:
    name: 'Meze Backend App'
    description: 'This is Mezeci Restaurant Backend Project'
    version: '@project.version@'